springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
  api-docs:
    path: /v3/api-docs
  show-actuator: true

spring:
  application:
    name: subscription-service
  kafka:
    bootstrap-servers: kafka:9092
    retryKey: retry
    errorKey: error
    topics:
      payment-status-updated:
        topic: payment-status-updated.0
        retryTopic: ${spring.kafka.topics.payment-status-updated.topic}.${spring.application.name}.${spring.kafka.retryKey}
        errorTopic: ${spring.kafka.topics.payment-status-updated.topic}.${spring.application.name}.${spring.kafka.errorKey}
        consumerGroup: ${spring.application.name}-payment-status-updated
        consumerGroupRetry: ${spring.application.name}-payment-status-updated-retry
        concurrencyLevel: 1
        autoOffsetReset: latest
  datasource:
    url: jdbc:postgresql://postgres:5432/subscription_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS
    time-zone: UTC
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

server:
  port: 8080

logging:
  level:
    root: INFO
    com.subscription: DEBUG
    org.springframework.kafka: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

