apiVersion: v1
kind: ConfigMap
metadata:
  name: subscription-service-config
data:
  database.url: "jdbc:postgresql://postgres:5432/subscription_db"
  spring.application.name: "subscription-service"
  server.port: "8080"
  spring.jpa.hibernate.ddl-auto: "validate"
  spring.jpa.show-sql: "false"
  spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.PostgreSQLDialect" 